version: '3'
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    container_name: "node-app-FC"
    networks:
      - application
    volumes:
      - ./back:/usr/app
      -  back_end_modules:/usr/app/node_modules

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "35729:35729"
    environment:
      - "CHOKIDAR_USEPOLLING=true"
    container_name: "react-app-FC"
    networks:
      - application
    volumes:
      - ./front:/usr/webapp
      - front_end_modules:/usr/webapp/node_modules

networks:
    application:
      driver: bridge
      
volumes:
    back_end_modules:
    front_end_modules: 